server:
  port: 8912
  tomcat:
    uri-encoding: UTF-8  

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muxin-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: xue13581321
    type: com.zaxxer.hikari.HikariDataSource
    
